# Generated by Django 4.2.8 on 2026-02-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="academic_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to academic module section (new structure)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_attendance_classes",
                to="academic.section",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to academic module enrollment (new structure)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_attendance_students",
                to="academic.enrollment",
            ),
        ),
    ]
