# Generated by Django 4.2.8 on 2026-02-06 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('portal_url', models.URLField(auto_created=True, blank=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(help_text='3-20 lowercase characters, no spaces', max_length=20, unique=True)),
                ('official_email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('school_type', models.CharField(choices=[('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('primary_secondary', 'Primary & Secondary'), ('higher_secondary', 'Higher Secondary Only'), ('coaching', 'Coaching Institute'), ('college', 'College')], max_length=20)),
                ('student_count', models.CharField(choices=[('<100', 'Less than 100'), ('100-300', '100-300'), ('300-600', '300-600'), ('600+', '600+')], max_length=10)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('other', 'Regional Language')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_enabled', models.BooleanField(default=True)),
                ('payroll_enabled', models.BooleanField(default=True)),
                ('timetable_enabled', models.BooleanField(default=True)),
                ('theme_color', models.CharField(default='#1f2937', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
    ]
