# Generated by Django 4.2.8 on 2026-02-06 10:20

from django.db import migrations, models
import django.db.models.deletion


def seed_roles_and_map_users(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    CustomUser = apps.get_model('users', 'CustomUser')
    Tenant = apps.get_model('tenants', 'Tenant')

    role_map = {
        'super_admin': 'Principal',
        'admin': 'Principal',
        'teacher': 'Teacher',
        'staff': 'Staff',
        'student': 'Student',
        'parent': 'Student',
    }

    for tenant in Tenant.objects.all():
        roles = {}
        for name, description in [
            ('Principal', 'School principal with full access.'),
            ('Teacher', 'Teacher with teaching responsibilities.'),
            ('Staff', 'Non-teaching staff member.'),
            ('Student', 'Student user with limited access.'),
        ]:
            role, _ = Role.objects.get_or_create(
                tenant=tenant,
                name=name,
                defaults={'description': description, 'is_system_role': True},
            )
            roles[name] = role

        users = CustomUser.objects.filter(tenant=tenant)
        for user in users:
            legacy_role = getattr(user, 'role', None)
            mapped = role_map.get(legacy_role, 'Student') if legacy_role else 'Student'
            user.role_fk_id = roles[mapped].id
            user.save(update_fields=['role_fk'])


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_images/%Y/%m/"
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_system_role", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="role_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.role",
            ),
        ),
        migrations.RunPython(seed_roles_and_map_users, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="role_fk",
            new_name="role",
        ),
    ]
