# Generated by Django 4.2.8 on 2026-02-06 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., '2025-2026'", max_length=50),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one session can be active per tenant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-start_date"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Grade 5', 'Class 10'", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="academic.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_classes",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["name"],
                "unique_together": {("tenant", "academic_session", "name")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., 'A', 'B', 'C'", max_length=10),
                ),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="academic.class",
                    ),
                ),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__name": "Teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_sections_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_sections",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["class_obj", "name"],
                "unique_together": {("tenant", "class_obj", "name")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=20)),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academic.academicsession",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academic.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__name": "Student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_enrollments",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "ordering": ["section", "roll_number"],
                "unique_together": {("tenant", "student", "academic_session")},
            },
        ),
    ]
