# Generated by Django 4.2.8 on 2026-02-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the module", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the module", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this module does"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Module version", max_length=20
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this module is available for installation",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier or emoji", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color theme for the module card",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_installed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the module is currently installed",
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the module was installed",
                    ),
                ),
                (
                    "uninstalled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the module was uninstalled",
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Module-specific configuration",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_installations",
                        to="plugins.module",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_modules",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Module",
                "verbose_name_plural": "Tenant Modules",
                "ordering": ["installed_at"],
                "unique_together": {("tenant", "module")},
            },
        ),
    ]
