# Generated by Django 4.2.8 on 2026-02-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_manage", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="plugins.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Permission",
                "verbose_name_plural": "Module Permissions",
                "ordering": ["module", "role"],
            },
        ),
    ]
