# Generated by Django 4.2.8 on 2026-02-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_profile_image_role_alter_customuser_role"),
        ("plugins", "0002_modulepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_permissions",
                to="users.role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modulepermission",
            unique_together={("module", "role")},
        ),
    ]
