# Generated by Django 4.2.8 on 2026-02-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Period 1', 'Lunch Break'", max_length=50
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "is_break",
                    models.BooleanField(
                        default=False, help_text="If true, no classes can be scheduled"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["start_time"],
                "unique_together": {("tenant", "name", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="SectionTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Override section room if needed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="academic.academicsession",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="academic.section",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__name": "Teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="timetable.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Timetable",
                "verbose_name_plural": "Section Timetables",
                "ordering": ["day_of_week", "time_slot__start_time"],
                "unique_together": {("tenant", "section", "day_of_week", "time_slot")},
            },
        ),
    ]
