# Generated by Django 4.2.8 on 2026-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontimetable',
            name='subject',
            field=models.CharField(help_text='Subject name (e.g., Mathematics, English)', max_length=100),
        ),
    ]
